import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {},
  container: {
    alignItems: "center",
    flex: 1,
  },
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  titleContainer: {
    marginTop: 20,
    width: "90%",
    padding: 30,
    borderWidth: 3,
    borderColor: "white",
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    alignItems: "center",
  },
  titleContainerText: {
    fontSize: 30,
    color: "white",
    fontFamily: "PostNoBillBold",
  },
  titleContainerTextId: {
    fontSize: 20,
    color: "white",
    fontFamily: "PostNoBillBold",
    marginTop: 10,
  },
  resultButton: {
    marginVertical: 20,
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    borderRadius: 10,
    height: 50,
    borderColor: "rgb(133, 133, 133)",
    borderWidth: 3,
    backgroundColor: "rgba(133, 133, 133, 0.1)",
  },
  resultText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "rgb(133, 133, 133)",
  },
  declinedButton: {
    marginVertical: 20,
    alignItems: "center",
    justifyContent: "center",
    width: "90%",
    borderRadius: 10,
    height: 50,
    borderColor: "rgb(248, 2, 2)",
    borderWidth: 3,
    backgroundColor: "rgba(248, 2, 2, 0.25)",
  },
  declinedText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "rgb(248, 2, 2)",
  },
});
